//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.09 at 10:43:52 AM CST 
//


package com.anyzm.wechat.message;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ToUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FromUserName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CreateTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MsgType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Content" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PicUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MediaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ThumbMediaId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Location_X" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Location_Y" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Scale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Event" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EventKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Ticket" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Latitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Longitude" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Precision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Recognition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScanCodeInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ScanType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ScanResult" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SendPicsInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PicList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="item" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="PicMd5Sum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SendLocationInfo" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Location_X" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Location_Y" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Scale" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Poiname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MsgId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TotalCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FilterCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SentCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ErrorCount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="KfAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FromKfAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ToKfAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "xml")
public class ReceiveXml {

    @XmlElement(name = "ToUserName", required = true)
    protected String toUserName;
    @XmlElement(name = "FromUserName", required = true)
    protected String fromUserName;
    @XmlElement(name = "CreateTime", required = true)
    protected String createTime;
    @XmlElement(name = "MsgType", required = true)
    protected String msgType;
    
	@XmlElement(name = "MediaLength")
    protected String mediaLength;
	
    @XmlElement(name = "Content")
    protected String content;
    @XmlElement(name = "PicUrl")
    protected String picUrl;
    @XmlElement(name = "MediaId")
    protected String mediaId;
    @XmlElement(name = "Format")
    protected String format;
    @XmlElement(name = "ThumbMediaId")
    protected String thumbMediaId;
    @XmlElement(name = "Location_X")
    protected String location_X;
    @XmlElement(name = "Location_Y")
    protected String location_Y;
    @XmlElement(name = "Scale")
    protected String scale;
    @XmlElement(name = "Label")
    protected String label;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Url")
    protected String url;
    @XmlElement(name = "Event")
    protected String event;
    @XmlElement(name = "EventKey")
    protected String eventKey;
    @XmlElement(name = "Ticket")
    protected String ticket;
    @XmlElement(name = "Latitude")
    protected String latitude;
    @XmlElement(name = "Longitude")
    protected String longitude;
    @XmlElement(name = "Precision")
    protected String precision;
    @XmlElement(name = "Recognition")
    protected String recognition;
    @XmlElement(name = "ScanCodeInfo")
    protected ScanCodeInfo scanCodeInfo;
    @XmlElement(name = "SendPicsInfo")
    protected SendPicsInfo sendPicsInfo;
    @XmlElement(name = "SendLocationInfo")
    protected SendLocationInfo sendLocationInfo;
    @XmlElement(name = "MsgId")
    protected String msgId;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "TotalCount")
    protected String totalCount;
    @XmlElement(name = "FilterCount")
    protected String filterCount;
    @XmlElement(name = "SentCount")
    protected String sentCount;
    @XmlElement(name = "ErrorCount")
    protected String errorCount;
    @XmlElement(name = "KfAccount")
    protected String kfAccount;
    @XmlElement(name = "FromKfAccount")
    protected String fromKfAccount;
    @XmlElement(name = "ToKfAccount")
    protected String toKfAccount;


    
    
    
    private String functionId;
    private String extendParam;
    private String yybqd;
    private String channelid;
    private String devicetype;
    private String model;
    private String ywlx;
    private String seatid;
    
    private String yyb;
    private String zzzh;
    private String userid;
    
    @XmlElement(name = "InfoType")
    protected String infoType;
    @XmlElement(name = "InfoCode")
    protected String infoCode;
    @XmlElement(name = "InfoValue")
    protected String infoValue;
    @XmlElement(name = "RecordId")
    protected String recordId;
    @XmlElement(name = "DataType")
    protected String dataType;
    @XmlElement(name = "ServiceType")
    protected String serviceType;
    
    

    public String getYyb() {
		return yyb;
	}

	public void setYyb(String yyb) {
		this.yyb = yyb;
	}

	public String getZzzh() {
		return zzzh;
	}

	public void setZzzh(String zzzh) {
		this.zzzh = zzzh;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}


	public String getSeatid() {
		return seatid;
	}

	public void setSeatid(String seatid) {
		this.seatid = seatid;
	}

	public String getYybqd() {
		return yybqd;
	}

	public void setYybqd(String yybqd) {
		this.yybqd = yybqd;
	}

	public String getChannelid() {
		return channelid;
	}

	public void setChannelid(String channelid) {
		this.channelid = channelid;
	}

	public String getDevicetype() {
		return devicetype;
	}

	public void setDevicetype(String devicetype) {
		this.devicetype = devicetype;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getYwlx() {
		return ywlx;
	}

	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}

	public String getFunctionId() {
		return functionId;
	}

	public void setFunctionId(String functionId) {
		this.functionId = functionId;
	}

	public String getExtendParam() {
		return extendParam;
	}

	public void setExtendParam(String extendParam) {
		this.extendParam = extendParam;
	}

	/**
     * Gets the value of the toUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToUserName() {
        return toUserName;
    }

    /**
     * Sets the value of the toUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToUserName(String value) {
        this.toUserName = value;
    }

    /**
     * Gets the value of the fromUserName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromUserName() {
        return fromUserName;
    }

    /**
     * Sets the value of the fromUserName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromUserName(String value) {
        this.fromUserName = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateTime(String value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the msgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgType() {
        return msgType;
    }

    /**
     * Sets the value of the msgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgType(String value) {
        this.msgType = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the picUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * Sets the value of the picUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPicUrl(String value) {
        this.picUrl = value;
    }

    /**
     * Gets the value of the mediaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * Sets the value of the mediaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaId(String value) {
        this.mediaId = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormat(String value) {
        this.format = value;
    }

    /**
     * Gets the value of the thumbMediaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThumbMediaId() {
        return thumbMediaId;
    }

    /**
     * Sets the value of the thumbMediaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThumbMediaId(String value) {
        this.thumbMediaId = value;
    }

    /**
     * Gets the value of the locationX property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation_X() {
        return location_X;
    }

    /**
     * Sets the value of the locationX property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation_X(String value) {
        this.location_X = value;
    }

    /**
     * Gets the value of the locationY property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation_Y() {
        return location_Y;
    }

    /**
     * Sets the value of the locationY property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation_Y(String value) {
        this.location_Y = value;
    }

    /**
     * Gets the value of the scale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScale() {
        return scale;
    }

    /**
     * Sets the value of the scale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScale(String value) {
        this.scale = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEvent(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the eventKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventKey() {
        return eventKey;
    }

    /**
     * Sets the value of the eventKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventKey(String value) {
        this.eventKey = value;
    }

    /**
     * Gets the value of the ticket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTicket() {
        return ticket;
    }

    /**
     * Sets the value of the ticket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTicket(String value) {
        this.ticket = value;
    }

    /**
     * Gets the value of the latitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * Sets the value of the latitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatitude(String value) {
        this.latitude = value;
    }

    /**
     * Gets the value of the longitude property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * Sets the value of the longitude property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongitude(String value) {
        this.longitude = value;
    }

    /**
     * Gets the value of the precision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecision() {
        return precision;
    }

    /**
     * Sets the value of the precision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecision(String value) {
        this.precision = value;
    }

    /**
     * Gets the value of the recognition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecognition() {
        return recognition;
    }

    /**
     * Sets the value of the recognition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecognition(String value) {
        this.recognition = value;
    }

    /**
     * Gets the value of the scanCodeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ScanCodeInfo }
     *     
     */
    public ScanCodeInfo getScanCodeInfo() {
        return scanCodeInfo;
    }

    /**
     * Sets the value of the scanCodeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanCodeInfo }
     *     
     */
    public void setScanCodeInfo(ScanCodeInfo value) {
        this.scanCodeInfo = value;
    }

    /**
     * Gets the value of the sendPicsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SendPicsInfo }
     *     
     */
    public SendPicsInfo getSendPicsInfo() {
        return sendPicsInfo;
    }

    /**
     * Sets the value of the sendPicsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendPicsInfo }
     *     
     */
    public void setSendPicsInfo(SendPicsInfo value) {
        this.sendPicsInfo = value;
    }

    /**
     * Gets the value of the sendLocationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SendLocationInfo }
     *     
     */
    public SendLocationInfo getSendLocationInfo() {
        return sendLocationInfo;
    }

    /**
     * Sets the value of the sendLocationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SendLocationInfo }
     *     
     */
    public void setSendLocationInfo(SendLocationInfo value) {
        this.sendLocationInfo = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the totalCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalCount() {
        return totalCount;
    }

    /**
     * Sets the value of the totalCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalCount(String value) {
        this.totalCount = value;
    }

    /**
     * Gets the value of the filterCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterCount() {
        return filterCount;
    }

    /**
     * Sets the value of the filterCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterCount(String value) {
        this.filterCount = value;
    }

    /**
     * Gets the value of the sentCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentCount() {
        return sentCount;
    }

    /**
     * Sets the value of the sentCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentCount(String value) {
        this.sentCount = value;
    }

    /**
     * Gets the value of the errorCount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCount() {
        return errorCount;
    }

    /**
     * Sets the value of the errorCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCount(String value) {
        this.errorCount = value;
    }

    /**
     * Gets the value of the kfAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKfAccount() {
        return kfAccount;
    }

    /**
     * Sets the value of the kfAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKfAccount(String value) {
        this.kfAccount = value;
    }

    /**
     * Gets the value of the fromKfAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromKfAccount() {
        return fromKfAccount;
    }

    /**
     * Sets the value of the fromKfAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromKfAccount(String value) {
        this.fromKfAccount = value;
    }

    /**
     * Gets the value of the toKfAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToKfAccount() {
        return toKfAccount;
    }

    /**
     * Sets the value of the toKfAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToKfAccount(String value) {
        this.toKfAccount = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ScanType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ScanResult" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scanType",
        "scanResult"
    })
    public static class ScanCodeInfo {

        @XmlElement(name = "ScanType", required = true)
        protected String scanType;
        @XmlElement(name = "ScanResult", required = true)
        protected String scanResult;

        /**
         * Gets the value of the scanType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScanType() {
            return scanType;
        }

        /**
         * Sets the value of the scanType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScanType(String value) {
            this.scanType = value;
        }

        /**
         * Gets the value of the scanResult property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScanResult() {
            return scanResult;
        }

        /**
         * Sets the value of the scanResult property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScanResult(String value) {
            this.scanResult = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Location_X" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Location_Y" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Scale" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Poiname" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "locationX",
        "locationY",
        "scale",
        "label",
        "poiname"
    })
    public static class SendLocationInfo {

        @XmlElement(name = "Location_X", required = true)
        protected String locationX;
        @XmlElement(name = "Location_Y", required = true)
        protected String locationY;
        @XmlElement(name = "Scale", required = true)
        protected String scale;
        @XmlElement(name = "Label", required = true)
        protected String label;
        @XmlElement(name = "Poiname", required = true)
        protected String poiname;

        /**
         * Gets the value of the locationX property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocationX() {
            return locationX;
        }

        /**
         * Sets the value of the locationX property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocationX(String value) {
            this.locationX = value;
        }

        /**
         * Gets the value of the locationY property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocationY() {
            return locationY;
        }

        /**
         * Sets the value of the locationY property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocationY(String value) {
            this.locationY = value;
        }

        /**
         * Gets the value of the scale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScale() {
            return scale;
        }

        /**
         * Sets the value of the scale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScale(String value) {
            this.scale = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

        /**
         * Gets the value of the poiname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoiname() {
            return poiname;
        }

        /**
         * Sets the value of the poiname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoiname(String value) {
            this.poiname = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PicList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="item" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="PicMd5Sum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "count",
        "picList"
    })
    public static class SendPicsInfo {

        @XmlElement(name = "Count", required = true)
        protected String count;
        @XmlElement(name = "PicList", required = true)
        protected PicList picList;

        /**
         * Gets the value of the count property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCount() {
            return count;
        }

        /**
         * Sets the value of the count property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCount(String value) {
            this.count = value;
        }

        /**
         * Gets the value of the picList property.
         * 
         * @return
         *     possible object is
         *     {@link PicList }
         *     
         */
        public PicList getPicList() {
            return picList;
        }

        /**
         * Sets the value of the picList property.
         * 
         * @param value
         *     allowed object is
         *     {@link PicList }
         *     
         */
        public void setPicList(PicList value) {
            this.picList = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="item" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PicMd5Sum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "item"
        })
        public static class PicList {

            @XmlElement(required = true)
            protected List<Item> item;

            /**
             * Gets the value of the item property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the item property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getItem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Item }
             * 
             * 
             */
            public List<Item> getItem() {
                if (item == null) {
                    item = new ArrayList<Item>();
                }
                return this.item;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PicMd5Sum" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "picMd5Sum"
            })
            public static class Item {

                @XmlElement(name = "PicMd5Sum", required = true)
                protected String picMd5Sum;

                /**
                 * Gets the value of the picMd5Sum property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPicMd5Sum() {
                    return picMd5Sum;
                }

                /**
                 * Sets the value of the picMd5Sum property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPicMd5Sum(String value) {
                    this.picMd5Sum = value;
                }

            }

        }

    }


	public String getMediaLength() {
		return mediaLength;
	}

	public void setMediaLength(String mediaLength) {
		this.mediaLength = mediaLength;
	}

	public String getInfoType() {
		return infoType;
	}

	public void setInfoType(String infoType) {
		this.infoType = infoType;
	}

	public String getInfoCode() {
		return infoCode;
	}

	public void setInfoCode(String infoCode) {
		this.infoCode = infoCode;
	}

	public String getInfoValue() {
		return infoValue;
	}

	public void setInfoValue(String infoValue) {
		this.infoValue = infoValue;
	}

	public String getRecordId() {
		return recordId;
	}

	public void setRecordId(String recordId) {
		this.recordId = recordId;
	}

	public String getDataType() {
		return dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}

	public String getServiceType() {
		return serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

}
